module.exports = {
  preset: 'ts-jest',
  testEnvironment: 'node',
  roots: ['<rootDir>/src'],
  testMatch: ['**/__tests__/**/*.test.ts', '**/?(*.)+(spec|test).ts'],
  testPathIgnorePatterns: ['/node_modules/', '/src/__tests__/setup.ts', '/src/__tests__/helpers/', '/src/__tests__/fixtures/'],
  transform: {
    '^.+\\.ts$': 'ts-jest',
  },
  collectCoverageFrom: [
    'src/**/*.ts',
    '!src/**/*.d.ts',
    '!src/**/*.test.ts',
    '!src/__tests__/**/*.ts',
    '!src/server.ts',
  ],
  coverageDirectory: 'coverage',
  coverageThreshold: {
    global: {
      branches: 5,
      functions: 8,
      lines: 10,
      statements: 10,
    },
    './src/modules/pm/services/auth.service.ts': {
      branches: 50,
      functions: 60,
      lines: 60,
      statements: 60,
    },
    './src/middleware/auth.ts': {
      branches: 50,
      functions: 60,
      lines: 60,
      statements: 60,
    },
    './src/modules/itsm/controllers/incident.controller.ts': {
      branches: 30,
      functions: 40,
      lines: 40,
      statements: 40,
    },
    './src/modules/itsm/controllers/problem.controller.ts': {
      branches: 30,
      functions: 40,
      lines: 40,
      statements: 40,
    },
    './src/modules/workflow-engine/services/workflowDefinition.service.ts': {
      branches: 30,
      functions: 40,
      lines: 40,
      statements: 40,
    },
  },
  moduleFileExtensions: ['ts', 'js', 'json'],
  verbose: true,
  testTimeout: 30000,
  forceExit: true,
  detectOpenHandles: true,
  };
